Repository Mystery-2-Dev/Java_Algorithms-, pull requests merged in 2020-10, with the labels that each got.

#11 #1 Added a java algorithm.
  lucky.java
Labels: hacktoberfest-accepted

#12 added java program on binary palindrome #1
  binaryPalindrome.java
Labels: hacktoberfest-accepted

#13 Added Selection Sort
  Sorting Algorithms/SelectionSort.java
Labels: hacktoberfest-accepted

#14 Added substitutionCipher #1
  substitutionCipher.java
Labels: hacktoberfest-accepted

#15 Added the Fisher Yates Shuffle Algorithm
  FisherYatesShuffle.java
Labels: hacktoberfest-accepted

#18 Shuffle Algorithm #1
  Main.java
Labels: Hacktoberfest accepeted

#19 #1
  RoutineDataManipulation.java
Labels: Hacktoberfest accepeted, hacktoberfest-accepted

#20 #1
  BinarySearch.java
Labels: Hacktoberfest accepeted, hacktoberfest-accepted

#21 #1
  ExtremeValues.java
Labels: Hacktoberfest accepeted, hacktoberfest-accepted

#22 #1
  ListIterator.java
Labels: Hacktoberfest accepeted, hacktoberfest-accepted
